### ISSUE TITLE
Maven artefacts

### ISSUE THREAD

**Issue by mkrogemann** [datasift/dropwizard-scala#1]
I could not locate the artefacts you mention in README.md.
What I was able to find is this:

  <groupId>com.massrelevance</groupId>
  <artifactId>dropwizard-scala_2.10</artifactId>
  <version>0.7.0</version>

Is this the version I should use?

**Comment by nicktelford** [comment]
Releases now exist in Maven Central for `0.7.1-2`, `0.8.5-1` and `0.9.2-1`. A release for `1.0.0-1` will be made once upstream has released `1.0.0` final.

They support the following Scala versions:

  * `0.7.1-2` - Scala `2.9.3` and `2.10.x`.
  * `0.8.5-1` - Scala `2.10.x` and `2.11.x`
  * `0.9.2-1` - Scala `2.10.x` and `2.11.x`
  * `1.0.0-1` (when released) - Scala `2.10.x` and `2.11.x`

See [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.datasift.dropwizard.scala%22) for a complete listing of available artifacts.
