### ISSUE TITLE
Freemarker support

### ISSUE THREAD

**Issue by tmaus** [datasift/dropwizard-scala#11]
Is support planned to render Scala primitives in e.g. Freemarker ?

Related topics:
 http://stackoverflow.com/questions/32201528/not-able-to-read-object-values-in-freemarker-template
https://github.com/btd/scala-freemarker

**Comment by nicktelford** [comment]
We have no plans to add Freemarker support in the (near) future. I would encourage you (or anyone else) to build that module yourself and publish it to the community :)
