### ISSUE TITLE
ProductResultSetMapper doesn't properly handle null fields

### ISSUE THREAD

**Issue by eschuchmann** [datasift/dropwizard-scala#15]
Deserializing non-Option types can erroneously result in a null value if a previous column has a null value.

```scala
case class DBFoo(bar: Option[Int], baz: String)
trait FooDao {
  @SqlQuery("SELECT bar, baz from foo limit 1")
  @SingleValueResult
  def getFoo(): Option[DBFoo]
}

"Jdbi-scala" should "properly deserialize non-options" in {
    handle.execute("CREATE TABLE `foo` (`bar` INT, `baz` varchar(128) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;")
    handle.execute("INSERT INTO foo (baz) VALUES (?)", "this isn't null")
    handle.commit()
    val dao = dbi.onDemand(classOf[FooDao])
    val foo: Option[DBFoo] = dao.getFoo()
    foo.get.baz should equal("this isn't null")
  }
```
This results in a failure:
`null did not equal "this isn't null"`

I believe this is due to the order in which ProductResultSetMapper is identifying null values:
```scala
override def map(index: Int,
                   rs: ResultSet,
                   ctx: StatementContext): A = {
...
      t match {
        // todo: do we need to explicitly match on the java variations of these types too?
        case _ if t.isAssignableFrom(classOf[Option[_]]) =>
          Option(rs.getObject(i))
        case _ if !t.isPrimitive && rs.wasNull =>
          null
...
        case _ if t.isAssignableFrom(classOf[String]) =>
          rs.getString(i)
...
      }
    }
```
The `case _ if !t.isPrimitive && rs.wasNull =>` line is using `rs.wasNull` which refers to the last retrieved field value (not the current field).  So if a previous column was null (and deserialized to an Option), the current field will get mapped to a null - even if the value of the current field is not null.  

From the ResultSet docs:
```
/**
Reports whether
     * the last column read had a value of SQL <code>NULL</code>.
     * Note that you must first call one of the getter methods
     * on a column to try to read its value and then call
     * the method <code>wasNull</code> to see if the value read was
     * SQL <code>NULL</code>.
*/
boolean wasNull() throws SQLException;
```

One possible workaround would be to call `rs.getObject(i)` just just prior to the call to `rs.wasNull` but this will result in retrieving every field twice.  Another option might be to not allow null values that are not mapped to an Option.

**Comment by nicktelford** [comment]
Thanks for spotting this and figuring out the issue!

I've fixed this in master, and it'll be in the next release.
