### ISSUE TITLE
Question on how to return query results as Seq

### ISSUE THREAD

**Issue by zbelzer** [datasift/dropwizard-scala#20]
We use the `@UseStringTemplate3StatementLocator` annotation and locate our SQL elsewhere, but I don't know if it matters.

We've been using the other dropwizard scala library to this point and thought that with this one we could change this:
```scala
  @SqlQuery
  def all: java.util.List[User]
```

To this:

```scala
  @SqlQuery
  def all: Seq[User]
```
Which would save us a lot of `.asScala` littered throughout our code.

But all I get is `No mapper registered for scala.collection.Seq` Do I have my wires crossed? Is this something that's actually supported or am I making this up?

I have added `dbi.registerContainerFactory(new IterableContainerFactory[scala.collection.Seq])` for what it's worth. I thought that would do it.

**Comment by zbelzer** [comment]
Ping.

**Comment by nicktelford** [comment]
This is actually broken due to a design constraint in jDBI: all "collection" types (i.e. to return multiple rows) need to implement `java.util.Iterable`, which Scala's collections don't. Unfortunately, there's no way to solve this without major changes to jDBI upstream.

**Comment by zbelzer** [comment]
Bummer. Thanks for the info.
