### ISSUE TITLE
Defaults for Options don't appear to be supported

### ISSUE THREAD

**Issue by zbelzer** [datasift/dropwizard-scala#6]
I'd be happy to be wrong, but when I declare something like:
```
@QueryParam("limit") limit: Option[Integer]
```

I would expect limit to be `None` when the code is run. Instead, it's `null`. On the off chance that it's supposed to be `null` when no default is actually supplied, I also tried:
```
@QueryParam("limit") limit: Option[Integer] = None
```

To the same effect.

We were previously using the massrelevance version of this library, but this looks much better and seems to be maintained, however, we seem to have lost our optional defaults.

With some direction, I'll happily try to fix this myself, but I'm pretty new to jersey's internals.

**Comment by nicktelford** [comment]
This definitely sounds like a problem I'd like to resolve, however I'm having some trouble reproducing it.

Would you mind adding a test that demonstrates the issue, perferably to `ScalaApplicationSpecIT`, but if you can't stomach that mass of code, a standalone test would be fine too.

Ideally, it should fail, I imagine with a 'NullPointerException`, or other reason that clearly demonstrates the default being `null`.

**Comment by nicktelford** [comment]
Could you also confirm the version of both Scala and dropwizard-scala that you're using?

**Comment by zbelzer** [comment]
Thanks for responding. I'm just trying to maintain the status quo while switching libraries here. Somehow defaults were supported before, so I'm curious as to whether or not I'm crazy or something bigger changed.

I have a PR with a couple tests, fwiw, but it sounds like this is working as expected per your comments above https://github.com/datasift/dropwizard-scala/pull/7

**Comment by nicktelford** [comment]
Yeah, so your tests pretty much confirm what I said above. I'm not sure how Scala's default arguments can ever have worked in Jersey, given the way they compile.

I'm afraid that, since this is the expected behaviour, there's nothing I can really do about it. Your best bet would be to use `@DefaultValue(Some(...))` instead of Scala's default arguments. Not ideal, but then Jersey doesn't exactly integrate great with Scala anyway.
